"""Add conversational AI models and fields

Revision ID: d9b4fa5c151b
Revises: bbfe9cfec645
Create Date: 2025-11-14 20:38:59.600258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9b4fa5c151b'
down_revision: Union[str, None] = 'bbfe9cfec645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_requirements',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_requirements_id'), 'information_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_information_requirements_template_id'), 'information_requirements', ['template_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('briefing_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extracted_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_briefing_id'), 'conversation_messages', ['briefing_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_timestamp'), 'conversation_messages', ['timestamp'], unique=False)
    op.add_column('briefings', sa.Column('information_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('briefings', sa.Column('gathered_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('briefings', sa.Column('conversation_summary', sa.Text(), nullable=True))
    op.add_column('template_versions', sa.Column('context_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_versions', 'context_prompt')
    op.drop_column('briefings', 'conversation_summary')
    op.drop_column('briefings', 'gathered_information')
    op.drop_column('briefings', 'information_state')
    op.drop_index(op.f('ix_conversation_messages_timestamp'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_briefing_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_information_requirements_template_id'), table_name='information_requirements')
    op.drop_index(op.f('ix_information_requirements_id'), table_name='information_requirements')
    op.drop_table('information_requirements')
    # ### end Alembic commands ###
