"""extend conversation for briefing support

Revision ID: 42bb03b9c2e0
Revises: 07a6a58c5f21
Create Date: 2025-10-26 04:13:18.506649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42bb03b9c2e0'
down_revision: Union[str, None] = '07a6a58c5f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('conversation_type', sa.String(length=50), nullable=False))
    op.add_column('conversations', sa.Column('end_client_id', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('briefing_id', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('whatsapp_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_conversations_briefing_id'), 'conversations', ['briefing_id'], unique=False)
    op.create_index(op.f('ix_conversations_end_client_id'), 'conversations', ['end_client_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'end_clients', ['end_client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_end_client_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_briefing_id'), table_name='conversations')
    op.drop_column('conversations', 'whatsapp_context')
    op.drop_column('conversations', 'briefing_id')
    op.drop_column('conversations', 'end_client_id')
    op.drop_column('conversations', 'conversation_type')
    # ### end Alembic commands ###
