"""add_briefing_model

Revision ID: 90d30d8d9f3d
Revises: 9c768bab4394
Create Date: 2025-10-26 10:34:20.008461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90d30d8d9f3d'
down_revision: Union[str, None] = '9c768bab4394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('end_client_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='briefingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('current_question_order', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['end_client_id'], ['end_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefings_end_client_id'), 'briefings', ['end_client_id'], unique=False)
    op.create_index(op.f('ix_briefings_id'), 'briefings', ['id'], unique=False)
    op.create_index(op.f('ix_briefings_template_version_id'), 'briefings', ['template_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_briefings_template_version_id'), table_name='briefings')
    op.drop_index(op.f('ix_briefings_id'), table_name='briefings')
    op.drop_index(op.f('ix_briefings_end_client_id'), table_name='briefings')
    op.drop_table('briefings')
    # ### end Alembic commands ###
