"""add delivered_at and read_at to whatsapp_messages

Revision ID: c4696da28d1a
Revises: e0d23f2a2007
Create Date: 2025-11-06 23:23:24.425749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4696da28d1a'
down_revision: Union[str, None] = 'e0d23f2a2007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'read_at')
    op.drop_column('whatsapp_messages', 'delivered_at')
    # ### end Alembic commands ###
