"""add current_question_index to whatsapp_session

Revision ID: bbfe9cfec645
Revises: 811662fad351
Create Date: 2025-11-10 09:46:01.700418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbfe9cfec645'
down_revision: Union[str, None] = '811662fad351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_sessions', sa.Column('current_question_index', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_sessions', 'current_question_index')
    # ### end Alembic commands ###
