"""add briefing analytics table

Revision ID: 6edbbc83c5c3
Revises: 90d30d8d9f3d
Create Date: 2025-10-26 16:04:08.131530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6edbbc83c5c3'
down_revision: Union[str, None] = '90d30d8d9f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefing_analytics',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('briefing_id', sa.Uuid(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefing_analytics_briefing_id'), 'briefing_analytics', ['briefing_id'], unique=True)
    op.create_index(op.f('ix_briefing_analytics_id'), 'briefing_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_briefing_analytics_id'), table_name='briefing_analytics')
    op.drop_index(op.f('ix_briefing_analytics_briefing_id'), table_name='briefing_analytics')
    op.drop_table('briefing_analytics')
    # ### end Alembic commands ###
